---
title: "Google Analytics Tools"
output: html_document
runtime: shiny
---
<!-- RUN -->
<!--
options(shiny.port = 1221)
#setwd("~/Google Drive/Work/Syntax/R/RMarkdown/")
rmarkdown::run("index.Rmd")
-->
```{r}
# knitr::opts_chunk$set(echo = TRUE)
# library(googleAnalyticsR)
require(rmarkdown)
require('googleAuthR')
print('test')
options("googleAuthR.webapp.client_id" = "472746344232-0vo77fupf9onf0bs3brrk2jc86b4vlj1.apps.googleusercontent.com")
options("googleAuthR.webapp.client_secret" = "u3EHSLSlUU-Wb0J4AI5RauV5")
options("googleAuthR.scopes.selected" = c("https://www.googleapis.com/auth/webmasters",
                                          "https://www.googleapis.com/auth/analytics",
                                          "https://www.googleapis.com/auth/tagmanager.readonly",
                                          "https://www.googleapis.com/auth/plus.me"))

gar_auth_jsUI("auth_demo", login_text = "Authorize Google")
```

```{r, echo=FALSE}
auth <- callModule(gar_auth_js, "auth_demo")
user_info <- reactive({

  req(auth())

  with_shiny(get_user_info,
             shiny_access_token = auth())
  checkTokenAPI(shiny_access_token = NULL)
})
```

```{r, echo=FALSE, error=FALSE}

vals <- reactiveValues(account = NULL)
valsReact <- reactiveValues(id = NULL)

# capture profiles
prof <- reactive({
  req(auth())
  authorize(token=auth())
  vals$account <- list_accounts()
  selectInput("account", 
    "Choose Account:", 
  vals$account$name, selectize = TRUE)
})

render2 <- reactive({
  req(prof())
  # store selected account id
  # if vals account values name is equal to selected account, get selected account id
  valsReact$id <- vals$account[vals$account$name == input$account,]$id 
  # store selected property data
  vals$property <- list_webproperties(accountId = valsReact$id) 
  selectInput("property", 
              "Choose Property:", 
              paste0(vals$property$name,sep = " ", vals$property$id))
})

render3 <- reactive({
  req(render2())
  valsReact$uaid <- vals$property[paste0(vals$property$name,sep = " ", vals$property$id) == input$property,]$id # store selected property id
  vals$view <- list_profiles(accountId = valsReact$id, webPropertyId = valsReact$uaid) # store selected view data
  selectInput("view", 
              "Choose View:", 
              vals$view$name)
  })

dateRange <- reactive({
  req(auth())
  dateRangeInput('dateRange',
      label = 'Date range input: yyyy-mm-dd',
      start = Sys.Date() - 2, end = Sys.Date() + 2
    )
})
  
renderUI({
  req(auth())
  dateRange()
})
```
